### ISSUE TITLE
Gender?

### ISSUE THREAD

**Issue by nicola-spb** [striker2000/petrovich#1]
Hi,

How can I get gender of user for using petrovich?

**Comment by striker2000** [comment]
Hi. The obtaining of user's gender is beyond the scope of the petrovich library. You may ask user's gender during a registration, or you may detect the gender relying on other user data. If the gender is unknown you can use `petrovich.Androgynous` constant in the methods calls.

**Comment by nicola-spb** [comment]
Thanks
